using DanceCompetitionHelper.Database.DisplayInfo;
using DanceCompetitionHelper.Database.Enum;
using DanceCompetitionHelper.Database.Tables;

namespace DanceCompetitionHelper
{
    public interface IDanceCompetitionHelper : IDisposable
    {
        #region Administration stuff
        void AddTestData();
        void Migrate();
        void CreateTableHistory(
            Guid competitionId,
            string comment = "Generated by User");

        #endregion // Administration stuff

        IEnumerable<Competition> GetCompetitions(
            bool includeInfos = false);
        IEnumerable<CompetitionClass> GetCompetitionClasses(
            Guid? competitionId,
            bool includeInfos = false,
            bool showAll = false);
        IEnumerable<Participant> GetParticipants(
            Guid? competitionId,
            Guid? competitionClassId,
            bool includeInfos = false,
            bool showAll = false);
        IEnumerable<AdjudicatorPanel> GetAdjudicatorPanels(
            Guid? competitionId,
            bool includeInfos = false);
        IEnumerable<Adjudicator> GetAdjudicators(
            Guid? competitionId,
            Guid? adjudicatorPanelId,
            bool includeInfos = false);

        Competition? GetCompetition(
            Guid? competitionId);

        Guid? FindCompetition(
            Guid? byAnyId);
        Guid? FindCompetitionClass(
            Guid? byAnyId);
        Guid? GetCompetition(
            string byName);
        Guid? GetCompetitionClass(
            string byName);
        CompetitionClass? GetCompetitionClass(
            Guid competitionId);

        Participant? GetParticipant(
            Guid participantId);

        AdjudicatorPanel? GetAdjudicatorPanel(
            Guid adjudicatorPanelId);

        Adjudicator? GetAdjudicator(
            Guid adjudicatorId);

        IEnumerable<MultipleStarter> GetMultipleStarter(
            Guid competitionId);

        #region Competition Crud

        void CreateCompetition(
            string competitionName,
            OrganizationEnum organization,
            string orgCompetitionId,
            string? competitionInfo,
            DateTime competitionDate,
            string? comment);

        void EditCompetition(
            Guid competitionId,
            string competitionName,
            OrganizationEnum organization,
            string orgCompetitionId,
            string? competitionInfo,
            DateTime competitionDate,
            string? comment);

        void RemoveCompetition(
            Guid competitionId);

        #endregion //  Competition Crud

        #region AdjudicatorPanel Crud

        void CreateAdjudicatorPanel(
            Guid competitionId,
            string name,
            string? comment);

        void EditAdjudicatorPanel(
            Guid adjudicatorPanelId,
            Guid competitionId,
            string name,
            string? comment);

        void RemoveAdjudicatorPanel(
            Guid adjudicatorPanelId);

        #endregion //  AdjudicatorPanel Crud

        #region Adjudicator Crud

        void CreateAdjudicator(
            Guid adjudicatorPanelId,
            string abbreviation,
            string name,
            string? comment);

        void EditAdjudicator(
            Guid adjudicatorId,
            Guid adjudicatorPanelId,
            string abbreviation,
            string name,
            string? comment);

        void RemoveAdjudicator(
            Guid adjudicatorId);

        #endregion //  Adjudicator Crud

        #region CompetitionClass Crud

        void CreateCompetitionClass(
            Guid competitionId,
            string competitionClassName,
            Guid adjudicatorPanelId,
            string orgClassId,
            string? discipline,
            string? ageClass,
            string? ageGroup,
            string? className,
            int minStartsForPromotion,
            double minPointsForPromotion,
            double pointsForFirts,
            int extraManualStarter,
            string? comment,
            bool ignore);

        void EditCompetitionClass(
            Guid competitionClassId,
            string competitionClassName,
            Guid adjudicatorPanelId,
            string orgClassId,
            string? discipline,
            string? ageClass,
            string? ageGroup,
            string? className,
            int minStartsForPromotion,
            double minPointsForPromotion,
            double pointsForFirst,
            int extraManualStarter,
            string? comment,
            bool ignore);

        void RemoveCompetitionClass(
            Guid competitionClassId);

        #endregion //  CompetitionClass Crud 

        #region Participant Crud

        void CreateParticipant(
            Guid competitionId,
            Guid competitionClassId,
            int startNumber,
            string namePartA,
            string? orgIdPartA,
            string? namePartB,
            string? orgIdPartB,
            string? clubName,
            string? orgIdClub,
            double orgPointsPartA,
            int orgStartsPartA,
            int? minStartsForPromotionPartA,
            bool? orgAlreadyPromotedPartA,
            string? OrgAlreadyPromotedInfoPartA,
            double? orgPointsPartB,
            int? orgStartsPartB,
            int? minStartsForPromotionPartB,
            bool? orgAlreadyPromotedPartB,
            string? OrgAlreadyPromotedInfoPartB,
            string? comment,
            bool ignore);

        void EditParticipant(
            Guid participantId,
            Guid competitionClassId,
            int startNumber,
            string namePartA,
            string? orgIdPartA,
            string? namePartB,
            string? orgIdPartB,
            string? clubName,
            string? orgIdClub,
            double orgPointsPartA,
            int orgStartsPartA,
            int? minStartsForPromotionPartA,
            bool? orgAlreadyPromotedPartA,
            string? OrgAlreadyPromotedInfoPartA,
            double? orgPointsPartB,
            int? orgStartsPartB,
            int? minStartsForPromotionPartB,
            bool? orgAlreadyPromotedPartB,
            string? OrgAlreadyPromotedInfoPartB,
            string? comment,
            bool ignore);

        void RemoveParticipant(
            Guid participantId);

        #endregion //  CompetitionClass Crud

        #region Importer

        List<string> ImportOrUpdateCompetition(
            OrganizationEnum Organization,
            string? OrgCompetitionId,
            ImportTypeEnum ImportType,
            IEnumerable<string>? filePaths);

        #endregion // Importer

    }
}
